# Generated by Django 5.0.6 on 2024-05-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
