# Generated by Django 5.0.6 on 2024-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_vehicles_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='rent_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
