# Generated by Django 5.0.6 on 2024-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_vehicles_rent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
