# Generated by Django 5.0.6 on 2024-05-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_vehicles_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
